### ISSUE TITLE
A config option to allow mobs to spawn in the void world

### ISSUE THREAD

**Issue by TheDeviantCrafter** [chaseoes/VoidWorld#2]
I'd like to shove a majority of my automation into a void world to save my FPS. Because of the number of entities it creates, one of the biggest FPS killers is a hostile mob farm. I'd like to request a config option which allows mobs to spawn in the simple void world. This would work identically to how they spawn in the overworld, ideally with all three spawn cycles (hostile, passive, water) all running.

The pack I'm working has no artificial mob spawning, so things like Ender IO spawners, cursed earth or WOOT aren't an option.

**Comment by chaseoes** [comment]
They can spawn as long as there are spawning spaces available, this is entirely dependent on your server or plugin configuration.
